# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"log_it": "00_tissue_spec_scores.ipynb",
         "tsi": "00_tissue_spec_scores.ipynb",
         "spm": "00_tissue_spec_scores.ipynb",
         "zscore": "00_tissue_spec_scores.ipynb",
         "tau": "00_tissue_spec_scores.ipynb",
         "calc_ts": "00_tissue_spec_scores.ipynb"}

modules = ["tissue_spec_scores.py"]

doc_url = "https://morriso1.github.io/tissue_spec_scores/"

git_url = "https://github.com/morriso1/tissue_spec_scores/tree/main/"

def custom_doc_links(name): return None
